[supervisord]
nodaemon=true
user=root

[program:php-fpm]
command=php-fpm

[program:nginx]
command=nginx -g "daemon off;"

[program:shredder]
command=/usr/local/bin/shredder
autostart=true
autorestart=true